name = "polyglot_formalisms"
version = "0.3.0"
description = "Gleam implementation of PolyglotFormalisms Common Library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "hyperpolymath", repo = "polyglot_formalisms_gleam" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
